import { MockDataItem } from "./type";

export const mockdata: MockDataItem[] = [
  {
    id: 5,
    board_id: 1,
    contract_id: 'CA-CALT-PC-6',
    account_id: 1,
    workflow_state: {
      phase: 'purchase',
      stage: 'supplier_acknowledged',
      state: 'success',
      externals: [],
      approval_state: 'none',
      allowed_actions: [],
      has_been_reviewed: true,
      allowed_transitions: [],
      completed_milestones: [
        '490dc57d-5afd-4207-804c-0680dde53060',
        'c3923074-b10c-4069-8e61-6e375c3a9482',
        'f7c54da2-b2f3-4189-9521-a3c05acdf311',
      ],
    },
    meta: {
      allowed_actions: [],
      active_revisions: [],
      completed_phases: [],
      completed_actions: [
        'create',
        'finalize_contract',
        'mark_as_sent',
        'mark_as_supplier_acknowledged',
      ],
    },
    fields: {
      attn: 'rdferf',
      title: 'htf',
      mobile: '9025044967',
      assignee: {
        id: 10,
        name: 'Alia Atreides',
        email: 'alia.atreides@dune.com',
      },
      merchant: {
        id: 37,
        name: 'TAMIL SELVAN P',
        type: 'Crm::Records::MyCard',
        email: 'tamilselvan962913@gmail.com',
        image: {
          url: '/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsiZGF0YSI6NiwicHVyIjoiYmxvYl9pZCJ9fQ==--f2f39315514b3c330fe9c4edc24aa099fb249df6/croppedFile.jpg?disposition=attachment',
          filename: 'croppedFile.jpg',
          preview_url:
            '/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsiZGF0YSI6NiwicHVyIjoiYmxvYl9pZCJ9fQ==--f2f39315514b3c330fe9c4edc24aa099fb249df6/eyJfcmFpbHMiOnsiZGF0YSI6eyJmb3JtYXQiOiJwbmciLCJyZXNpemVfdG9fbGltaXQiOlsxMDAsMTAwXX0sInB1ciI6InZhcmlhdGlvbiJ9fQ==--bc57dcb95e5b7bade61cab55d8227a2249781e3a/croppedFile.jpg',
          content_type: 'image/png',
        },
        address: '31, Thendral Nagar,Tirupattur',
        initials: 'TSP',
        phone_no: '09025044967',
      },
      supplier: {
        id: 7,
        name: 'VaisnaviTex',
        type: 'Crm::Records::Supplier',
        email: 'vaisnavitex@buyer.com',
        address: 'sadfasdfasdfasdf',
        initials: 'VAI',
        phone_no: '399999999',
      },
      enquiries: [1],
      description: 'htf',
      loading_port: {
        id: 'chennai',
        label: 'Chennai',
        value: {
          id: 138,
          label: 'chennai',
          order: 20,
          value: 'chennai',
        },
      },
      contract_date: '2024-10-14T18:30:00.000Z',
      delivery_date: '2024-10-14T18:30:00.000Z',
      shipment_mode: {
        id: 'air',
        label: 'Air',
        value: {
          id: 134,
          label: 'air',
          order: 10,
          value: 'air',
        },
      },
      origin_country: {
        id: 'india',
        label: 'India',
        value: {
          id: 136,
          label: 'india',
          order: 10,
          value: 'india',
        },
      },
    },
    state: 'success',
    order_items: [
      {
        id: 1,
        title: 'htfyku,',
        board_id: 1,
        account_id: 1,
        meta: {
          allowed_actions: ['change_assignee'],
          active_revisions: [],
          completed_phases: ['init', 'design', 'supplier_quotes', 'buyer_quotes', 'sales_contract'],
          completed_actions: [
            'create',
            'assign_design_team',
            'upload_design',
            'update_quote',
            'select_quote',
            'finalize_buyer_quote',
            'confirm_customer_received_quote',
            'confirm_customer_acceptance',
          ],
        },
        workflow_state: {
          phase: 'purchase_contract',
          stage: 'purchase:supplier_acknowledged',
          state: 'success',
          externals: ['sales_contract', 'purchase_contract'],
          approval_state: 'none',
          allowed_actions: [],
          has_been_reviewed: true,
          allowed_transitions: [],
          completed_milestones: [
            '81440a8a-4601-4851-a204-993fd87285e3',
            'a6f04fe1-a29d-4edc-b5bb-917c4fb69279',
            '1ef580d7-5850-40a5-b10d-f24359492324',
            '57779ccd-100c-4251-902c-2895234e606a',
            '0c6283f5-86e9-42fd-b919-2e5cf6b379f1',
            '6833b1b0-a1bf-4efe-aa9d-84b63dbd9e24',
            '5bba2f07-279d-45bb-a8c7-aae2cc8b84b9',
            '5770a7b1-1532-43d4-afba-8e1b480bf7ad',
            'dc0b931f-56ac-4514-87e2-0b80570fe006',
            '31332cd7-864e-479b-9f4d-a4e706ff64c7',
          ],
        },
        available_for: null,
        code: 'CALT-6',
        attachments: [
          {
            sample_image: {
              filename: 'croppedFile.jpg',
              content_type: 'image/png',
              url: '/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsiZGF0YSI6MSwicHVyIjoiYmxvYl9pZCJ9fQ==--beace5a37caa98f69aead3ebc4ef5cd20f356d4d/croppedFile.jpg?disposition=attachment',
              preview_url:
                '/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsiZGF0YSI6MSwicHVyIjoiYmxvYl9pZCJ9fQ==--beace5a37caa98f69aead3ebc4ef5cd20f356d4d/eyJfcmFpbHMiOnsiZGF0YSI6eyJmb3JtYXQiOiJwbmciLCJyZXNpemVfdG9fbGltaXQiOlsxMDAsMTAwXX0sInB1ciI6InZhcmlhdGlvbiJ9fQ==--bc57dcb95e5b7bade61cab55d8227a2249781e3a/croppedFile.jpg',
            },
          },
          {
            spec_sheet: {
              filename: 'download.jpeg',
              content_type: 'image/jpeg',
              url: '/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsiZGF0YSI6MywicHVyIjoiYmxvYl9pZCJ9fQ==--788ab2bb7164e40179f318b61b98d97e03c1adee/download.jpeg?disposition=attachment',
              preview_url:
                '/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsiZGF0YSI6MywicHVyIjoiYmxvYl9pZCJ9fQ==--788ab2bb7164e40179f318b61b98d97e03c1adee/eyJfcmFpbHMiOnsiZGF0YSI6eyJmb3JtYXQiOiJqcGVnIiwicmVzaXplX3RvX2xpbWl0IjpbMTAwLDEwMF19LCJwdXIiOiJ2YXJpYXRpb24ifX0=--598a2817a7a7c590331f007a0bb237facb8049c5/download.jpeg',
            },
          },
          {
            trims_file: {
              filename: 'download.jpeg',
              content_type: 'image/jpeg',
              url: '/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsiZGF0YSI6NCwicHVyIjoiYmxvYl9pZCJ9fQ==--01c293fcf7e1c6d841016c5a85570db80e3fd5a3/download.jpeg?disposition=attachment',
              preview_url:
                '/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsiZGF0YSI6NCwicHVyIjoiYmxvYl9pZCJ9fQ==--01c293fcf7e1c6d841016c5a85570db80e3fd5a3/eyJfcmFpbHMiOnsiZGF0YSI6eyJmb3JtYXQiOiJqcGVnIiwicmVzaXplX3RvX2xpbWl0IjpbMTAwLDEwMF19LCJwdXIiOiJ2YXJpYXRpb24ifX0=--598a2817a7a7c590331f007a0bb237facb8049c5/download.jpeg',
            },
          },
          {
            tech_pack: {
              filename: 'download.jpeg',
              content_type: 'image/jpeg',
              url: '/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsiZGF0YSI6NSwicHVyIjoiYmxvYl9pZCJ9fQ==--f0cada5d5505854a05b4b83f9bfbda8134acba00/download.jpeg?disposition=attachment',
              preview_url:
                '/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsiZGF0YSI6NSwicHVyIjoiYmxvYl9pZCJ9fQ==--f0cada5d5505854a05b4b83f9bfbda8134acba00/eyJfcmFpbHMiOnsiZGF0YSI6eyJmb3JtYXQiOiJqcGVnIiwicmVzaXplX3RvX2xpbWl0IjpbMTAwLDEwMF19LCJwdXIiOiJ2YXJpYXRpb24ifX0=--598a2817a7a7c590331f007a0bb237facb8049c5/download.jpeg',
            },
          },
        ],
        milestones: [
          {
            id: 1,
            title: 'Expecting: `Ready` Completion',
            description: 'Expecting: `Ready` Completion',
            status: 'success',
            expected_completion_date: '2024-10-08T09:02:52.570Z',
            completion_date: '2024-10-08T12:38:29.478Z',
            duration: '2H',
            key: '81440a8a-4601-4851-a204-993fd87285e3:1',
            revision: null,
          },
          {
            id: 3,
            title: 'Expecting: `Design Team Assigned` Completion',
            description: 'Expecting: `Design Team Assigned` Completion',
            status: 'success',
            expected_completion_date: '2024-10-08T14:38:29.478Z',
            completion_date: '2024-10-08T12:39:50.660Z',
            duration: '2H',
            key: 'a6f04fe1-a29d-4edc-b5bb-917c4fb69279:1',
            revision: null,
          },
          {
            id: 11,
            title: 'Expecting: `Buyer Quote Finalized` Completion',
            description: 'Expecting: `Buyer Quote Finalized` Completion',
            status: 'success',
            expected_completion_date: '2024-10-08T14:41:24.333Z',
            completion_date: '2024-10-08T12:41:33.787Z',
            duration: '2H',
            key: '6833b1b0-a1bf-4efe-aa9d-84b63dbd9e24:1',
            revision: null,
          },
          {
            id: 5,
            title: 'Expecting: `Design Uploaded` Completion',
            description: 'Expecting: `Design Uploaded` Completion',
            status: 'success',
            expected_completion_date: '2024-10-08T14:39:50.660Z',
            completion_date: '2024-10-08T12:40:18.135Z',
            duration: '2H',
            key: '1ef580d7-5850-40a5-b10d-f24359492324:1',
            revision: null,
          },
          {
            id: 7,
            title: 'Expecting: `Quote Received` Completion',
            description: 'Expecting: `Quote Received` Completion',
            status: 'success',
            expected_completion_date: '2024-10-08T14:40:18.135Z',
            completion_date: '2024-10-08T12:40:52.391Z',
            duration: '2H',
            key: '57779ccd-100c-4251-902c-2895234e606a:1',
            revision: null,
          },
          {
            id: 9,
            title: 'Expecting: `Quote Selected` Completion',
            description: 'Expecting: `Quote Selected` Completion',
            status: 'success',
            expected_completion_date: '2024-10-08T14:40:52.391Z',
            completion_date: '2024-10-08T12:41:24.333Z',
            duration: '2H',
            key: '0c6283f5-86e9-42fd-b919-2e5cf6b379f1:1',
            revision: null,
          },
          {
            id: 13,
            title: 'Expecting: `Buyer Received Quote` Completion',
            description: 'Expecting: `Buyer Received Quote` Completion',
            status: 'success',
            expected_completion_date: '2024-10-08T14:41:33.787Z',
            completion_date: '2024-10-08T12:41:42.093Z',
            duration: '2H',
            key: '5bba2f07-279d-45bb-a8c7-aae2cc8b84b9:1',
            revision: null,
          },
          {
            id: 15,
            title: 'Expecting: `Buyer Accepted Quote` Completion',
            description: 'Expecting: `Buyer Accepted Quote` Completion',
            status: 'success',
            expected_completion_date: '2024-10-08T14:41:42.093Z',
            completion_date: '2024-10-10T12:07:47.914Z',
            duration: '2H',
            key: '5770a7b1-1532-43d4-afba-8e1b480bf7ad:1',
            revision: null,
          },
          {
            id: 17,
            title: 'Expecting: `Sales Contract` Completion',
            description: 'Expecting: `Sales Contract` Completion',
            status: 'success',
            expected_completion_date: '2024-10-14T07:34:59.062Z',
            completion_date: '2024-10-14T05:36:53.135Z',
            duration: '2H',
            key: 'dc0b931f-56ac-4514-87e2-0b80570fe006:1',
            revision: null,
          },
          {
            id: 19,
            title: 'Expecting: `Purchase Contract` Completion',
            description: 'Expecting: `Purchase Contract` Completion',
            status: 'success',
            expected_completion_date: '2024-10-15T06:59:18.885Z',
            completion_date: '2024-10-15T04:59:18.885Z',
            duration: '2H',
            key: '31332cd7-864e-479b-9f4d-a4e706ff64c7:1',
            revision: null,
          },
        ],
        change_requests: [],
        fields: {
          style_no: 'Vj24-CORL150CD',
          colour: 'PINK',
          gsm: '133',
          combo: '2',
          title: 'htfyku,',
          client: {
            id: '3',
            name: 'Camel',
            type: 'client',
            email: 'camel@buyer.com',
            address: 'sadfasdfasdfasdf',
            initials: 'CAM',
            phone_no: '399999999',
          },
          packing: 'Flat',
          assignee: {
            id: '2',
            name: 'Shaddam Iv',
            email: 'shaddam.iv@dune.com',
          },
          quantity: '2244',
          age_group: 'male',
          tech_pack: {
            id: 5,
            dirs: ['CALT-6'],
            name: 'tech_packstkwbo',
            extension: 'jpeg',
            organisation: 'dune',
          },
          spec_sheet: {
            id: 3,
            dirs: ['CALT-6'],
            name: 'spec_sheetwgr9gv',
            extension: 'jpeg',
            organisation: 'dune',
          },
          trims_file: {
            id: 4,
            dirs: ['CALT-6'],
            name: 'trims_fileaf0ut1',
            extension: 'jpeg',
            organisation: 'dune',
          },
          buyer_quote: {
            value: '12000',
            currency: 'usd',
          },
          description: 'LADIES FASHION TEE',
          design_team: {
            id: '4',
            name: 'Alpha',
            type: 'design_team',
            email: 'alpha@buyer.com',
            address: 'sadfasdfasdfasdf',
            initials: 'ALP',
            phone_no: '399999999',
          },
          sample_image: {
            id: 1,
            dirs: ['CALT-6'],
            name: 'sample_imagefwn1gg',
            extension: 'jpg',
            organisation: 'dune',
          },
          packing_ratio: {
            '0': {
              key: 'xl',
              value: '123',
            },
            '1': {
              key: 'l',
              value: '123',
            },
            '2': {
              key: 'm',
              value: '123',
            },
            '3': {
              key: 's',
              value: '122',
            },
          },
          fabric_quality: 'kutyf',
          sales_contract: 'CA-CALT-SC-6',
          purchase_contract: 'CA-CALT-PC-6',
          supplier_quotations: {
            '0': {
              id: '7',
              name: 'VaisnaviTex',
              type: 'Crm::Records::Supplier',
              email: 'vaisnavitex@buyer.com',
              value: '9000',
              address: 'sadfasdfasdfasdf',
              currency: 'inr',
              initials: 'VAI',
              phone_no: '399999999',
            },
            '1': {
              id: '9',
              name: 'MadhanTex',
              type: 'Crm::Records::Supplier',
              email: 'madhantex@buyer.com',
              value: '10000',
              address: 'sadfasdfasdfasdf',
              currency: 'inr',
              initials: 'MAD',
              phone_no: '399999999',
            },
          },
          selected_supplier_quote: {
            id: '7',
            name: 'VaisnaviTex',
            type: 'Crm::Records::Supplier',
            email: 'vaisnavitex@buyer.com',
            value: '9000',
            address: 'sadfasdfasdfasdf',
            currency: 'inr',
            initials: 'VAI',
            phone_no: '399999999',
          },
          order_item_list: [
            {
              fair_article: 2312375001,
              tag_article: 2345974001,
              tag_description: 'Ladies Tee S/S CORL150CD AW24, S',
              ean_code: 2200015600884,
              regional_wise_quantity: {
                aux: 6,
                dxb: 6,
                aln: 2,
                omn: 6,
                qtr: 6,
                bah: 4,
                kwt: 4,
                ksa: 6,
              },
              selling_price: {
                sp_ae: 45.0,
                sp_qa: 45.0,
                sp_sa: 49.0,
                bh: 4.9,
                sp_om: 4.5,
                sp_kw: 4.0,
              },
            },
            {
              fair_article: 2312375002,
              tag_article: 2345974002,
              tag_description: 'Ladies Tee S/S CORL150CD AW24, M',
              ean_code: 2200015600891,
              regional_wise_quantity: {
                aux: 12,
                dxb: 12,
                aln: 4,
                omn: 12,
                qtr: 12,
                bah: 8,
                kwt: 8,
                ksa: 12,
              },
              selling_price: {
                sp_ae: 45.0,
                sp_qa: 45.0,
                sp_sa: 49.0,
                bh: 4.9,
                sp_om: 4.5,
                sp_kw: 4.0,
              },
            },
            {
              fair_article: 2312375003,
              tag_article: 2345974003,
              tag_description: 'Ladies Tee S/S CORL150CD AW24, L',
              ean_code: 2200015600907,
              regional_wise_quantity: {
                aux: 24,
                dxb: 24,
                aln: 8,
                omn: 24,
                qtr: 24,
                bah: 16,
                kwt: 16,
                ksa: 24,
              },
              selling_price: {
                sp_ae: 45.0,
                sp_qa: 45.0,
                sp_sa: 49.0,
                bh: 4.9,
                sp_om: 4.5,
                sp_kw: 4.0,
              },
            },
            {
              fair_article: 2312375004,
              tag_article: 2345974004,
              tag_description: 'Ladies Tee S/S CORL150CD AW24, XL',
              ean_code: 2200015600914,
              regional_wise_quantity: {
                aux: 18,
                dxb: 18,
                aln: 6,
                omn: 18,
                qtr: 18,
                bah: 12,
                kwt: 12,
                ksa: 18,
              },
              selling_price: {
                sp_ae: 45.0,
                sp_qa: 45.0,
                sp_sa: 49.0,
                bh: 4.9,
                sp_om: 4.5,
                sp_kw: 4.0,
              },
            },
            {
              fair_article: 2312375005,
              tag_article: 2345974005,
              tag_description: 'Ladies Tee S/S CORL150CD AW24, XXl',
              ean_code: 2200015600921,
              regional_wise_quantity: {
                aux: 12,
                dxb: 12,
                aln: 4,
                omn: 12,
                qtr: 12,
                bah: 8,
                kwt: 8,
                ksa: 12,
              },
              selling_price: {
                sp_ae: 45.0,
                sp_qa: 45.0,
                sp_sa: 49.0,
                bh: 4.9,
                sp_om: 4.5,
                sp_kw: 4.0,
              },
            },
          ],
        },
      },
      {
        id: 3,
        title: 'Enquiry01',
        board_id: 1,
        account_id: 1,
        meta: {
          allowed_actions: ['change_assignee', 'update_quote'],
          active_revisions: [],
          completed_phases: ['init'],
          completed_actions: ['create', 'assign_design_team', 'upload_design'],
        },
        workflow_state: {
          phase: 'design',
          stage: 'design_uploaded',
          state: 'in_progress',
          externals: [],
          approval_state: 'approved',
          allowed_actions: ['update_quote'],
          has_been_reviewed: true,
          allowed_transitions: [
            {
              to: 'quote_received',
              from: 'design_uploaded',
            },
          ],
          completed_milestones: [
            '81440a8a-4601-4851-a204-993fd87285e3',
            'a6f04fe1-a29d-4edc-b5bb-917c4fb69279',
          ],
        },
        available_for: null,
        code: 'CALT-23',
        attachments: [
          {
            sample_image: {
              filename: 'croppedFile.jpg',
              content_type: 'image/png',
              url: '/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsiZGF0YSI6OSwicHVyIjoiYmxvYl9pZCJ9fQ==--5eb772be74e44ad0756fd2ac27fa2ffd367a1ebb/croppedFile.jpg?disposition=attachment',
              preview_url:
                '/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsiZGF0YSI6OSwicHVyIjoiYmxvYl9pZCJ9fQ==--5eb772be74e44ad0756fd2ac27fa2ffd367a1ebb/eyJfcmFpbHMiOnsiZGF0YSI6eyJmb3JtYXQiOiJwbmciLCJyZXNpemVfdG9fbGltaXQiOlsxMDAsMTAwXX0sInB1ciI6InZhcmlhdGlvbiJ9fQ==--bc57dcb95e5b7bade61cab55d8227a2249781e3a/croppedFile.jpg',
            },
          },
          {
            spec_sheet: {
              filename: 'nature.jpg',
              content_type: 'image/jpeg',
              url: '/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsiZGF0YSI6NzEsInB1ciI6ImJsb2JfaWQifX0=--f69e292aa664167a8adb1b03532a953f49a62cd9/nature.jpg?disposition=attachment',
              preview_url:
                '/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsiZGF0YSI6NzEsInB1ciI6ImJsb2JfaWQifX0=--f69e292aa664167a8adb1b03532a953f49a62cd9/eyJfcmFpbHMiOnsiZGF0YSI6eyJmb3JtYXQiOiJqcGciLCJyZXNpemVfdG9fbGltaXQiOlsxMDAsMTAwXX0sInB1ciI6InZhcmlhdGlvbiJ9fQ==--ba0594a2d11cf6ee50195da1c0a9cb4ec376d39c/nature.jpg',
            },
          },
          {
            trims_file: {
              filename: 'nature.jpg',
              content_type: 'image/jpeg',
              url: '/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsiZGF0YSI6NzIsInB1ciI6ImJsb2JfaWQifX0=--38f83cee780a69077ec165385c56d1a6ae158ee0/nature.jpg?disposition=attachment',
              preview_url:
                '/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsiZGF0YSI6NzIsInB1ciI6ImJsb2JfaWQifX0=--38f83cee780a69077ec165385c56d1a6ae158ee0/eyJfcmFpbHMiOnsiZGF0YSI6eyJmb3JtYXQiOiJqcGciLCJyZXNpemVfdG9fbGltaXQiOlsxMDAsMTAwXX0sInB1ciI6InZhcmlhdGlvbiJ9fQ==--ba0594a2d11cf6ee50195da1c0a9cb4ec376d39c/nature.jpg',
            },
          },
          {
            tech_pack: {
              filename: 'nature.jpg',
              content_type: 'image/jpeg',
              url: '/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsiZGF0YSI6NzMsInB1ciI6ImJsb2JfaWQifX0=--dbc2d1615df80d87b0809af2244f092026056a13/nature.jpg?disposition=attachment',
              preview_url:
                '/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsiZGF0YSI6NzMsInB1ciI6ImJsb2JfaWQifX0=--dbc2d1615df80d87b0809af2244f092026056a13/eyJfcmFpbHMiOnsiZGF0YSI6eyJmb3JtYXQiOiJqcGciLCJyZXNpemVfdG9fbGltaXQiOlsxMDAsMTAwXX0sInB1ciI6InZhcmlhdGlvbiJ9fQ==--ba0594a2d11cf6ee50195da1c0a9cb4ec376d39c/nature.jpg',
            },
          },
        ],
        milestones: [
          {
            id: 23,
            title: 'Expecting: `Design Team Assigned` Completion',
            description: 'Expecting: `Design Team Assigned` Completion',
            status: 'success',
            expected_completion_date: '2024-10-09T11:17:55.276Z',
            completion_date: '2024-10-15T04:54:54.734Z',
            duration: '2H',
            key: 'a6f04fe1-a29d-4edc-b5bb-917c4fb69279:3',
            revision: null,
          },
          {
            id: 25,
            title: 'Expecting: `Design Uploaded` Completion',
            description: 'Expecting: `Design Uploaded` Completion',
            status: 'defined',
            expected_completion_date: '2024-10-15T06:54:54.734Z',
            completion_date: null,
            duration: '2H',
            key: '1ef580d7-5850-40a5-b10d-f24359492324:3',
            revision: null,
          },
          {
            id: 21,
            title: 'Expecting: `Ready` Completion',
            description: 'Expecting: `Ready` Completion',
            status: 'success',
            expected_completion_date: '2024-10-09T11:17:48.259Z',
            completion_date: '2024-10-09T09:17:55.276Z',
            duration: '2H',
            key: '81440a8a-4601-4851-a204-993fd87285e3:3',
            revision: null,
          },
          {
            id: 27,
            title: 'Expecting: `Quote Received` Completion',
            description: 'Expecting: `Quote Received` Completion',
            status: 'defined',
            expected_completion_date: '2024-10-15T08:54:54.734Z',
            completion_date: null,
            duration: '2H',
            key: '57779ccd-100c-4251-902c-2895234e606a:3',
            revision: null,
          },
          {
            id: 29,
            title: 'Expecting: `Quote Selected` Completion',
            description: 'Expecting: `Quote Selected` Completion',
            status: 'defined',
            expected_completion_date: '2024-10-15T10:54:54.734Z',
            completion_date: null,
            duration: '2H',
            key: '0c6283f5-86e9-42fd-b919-2e5cf6b379f1:3',
            revision: null,
          },
          {
            id: 31,
            title: 'Expecting: `Buyer Quote Finalized` Completion',
            description: 'Expecting: `Buyer Quote Finalized` Completion',
            status: 'defined',
            expected_completion_date: '2024-10-15T12:54:54.734Z',
            completion_date: null,
            duration: '2H',
            key: '6833b1b0-a1bf-4efe-aa9d-84b63dbd9e24:3',
            revision: null,
          },
          {
            id: 33,
            title: 'Expecting: `Buyer Received Quote` Completion',
            description: 'Expecting: `Buyer Received Quote` Completion',
            status: 'defined',
            expected_completion_date: '2024-10-15T14:54:54.734Z',
            completion_date: null,
            duration: '2H',
            key: '5bba2f07-279d-45bb-a8c7-aae2cc8b84b9:3',
            revision: null,
          },
          {
            id: 35,
            title: 'Expecting: `Buyer Accepted Quote` Completion',
            description: 'Expecting: `Buyer Accepted Quote` Completion',
            status: 'defined',
            expected_completion_date: '2024-10-15T16:54:54.734Z',
            completion_date: null,
            duration: '2H',
            key: '5770a7b1-1532-43d4-afba-8e1b480bf7ad:3',
            revision: null,
          },
          {
            id: 37,
            title: 'Expecting: `Sales Contract` Completion',
            description: 'Expecting: `Sales Contract` Completion',
            status: 'defined',
            expected_completion_date: '2024-10-15T18:54:54.734Z',
            completion_date: null,
            duration: '2H',
            key: 'dc0b931f-56ac-4514-87e2-0b80570fe006:3',
            revision: null,
          },
          {
            id: 39,
            title: 'Expecting: `Purchase Contract` Completion',
            description: 'Expecting: `Purchase Contract` Completion',
            status: 'defined',
            expected_completion_date: '2024-10-15T20:54:54.734Z',
            completion_date: null,
            duration: '2H',
            key: '31332cd7-864e-479b-9f4d-a4e706ff64c7:3',
            revision: null,
          },
        ],
        change_requests: [],
        fields: {
          style_no: 'Vj24-CORL151CD',
          colour: 'CLEAR SKY',
          gsm: '2',
          combo: '2',
          title: 'Enquiry01',
          client: {
            id: '2',
            name: 'Lifestyle',
            type: 'client',
            email: 'lifestyle@buyer.com',
            address: 'sadfasdfasdfasdf',
            initials: 'LIF',
            phone_no: '399999999',
          },
          packing: 'Regular',
          assignee: {
            id: '2',
            name: 'Shaddam Iv',
            email: 'shaddam.iv@dune.com',
          },
          quantity: '10000',
          age_group: 'male',
          tech_pack: {
            id: 72,
            dirs: ['CALT-23'],
            name: 'tech_packgnmpfr',
            extension: 'jpg',
            organisation: 'dune',
          },
          spec_sheet: {
            id: 70,
            dirs: ['CALT-23'],
            name: 'spec_sheet7a9pts',
            extension: 'jpg',
            organisation: 'dune',
          },
          trims_file: {
            id: 71,
            dirs: ['CALT-23'],
            name: 'trims_file0iy1m5',
            extension: 'jpg',
            organisation: 'dune',
          },
          description: 'LADIES FASHION TEE',
          design_team: {
            id: '5',
            name: 'Beta',
            type: 'design_team',
            email: 'beta@buyer.com',
            address: 'sadfasdfasdfasdf',
            initials: 'BET',
            phone_no: '399999999',
          },
          sample_image: {
            id: 8,
            dirs: ['CALT-23'],
            name: 'sample_imageigzzyn',
            extension: 'jpg',
            organisation: 'dune',
          },
          packing_ratio: {
            '0': {
              key: 'xs',
              value: '5000',
            },
            '1': {
              key: 'l',
              value: '5000',
            },
          },
          fabric_quality: '2',
          buyer_quote: {
            value: ' ',
            currency: ' ',
          },
          sales_contract: '',
          purchase_contract: '',
          supplier_quotations: {},
          selected_supplier_quote: {
            id: '',
            name: '',
            type: '',
            email: '',
            value: '',
            address: '',
            currency: '',
            initials: '',
            phone_no: '',
          },
          order_item_list: [
            {
              fair_article: 2312376001,
              tag_article: 2345975001,
              tag_description: 'Ladies Tee S/S CORL150CD AW24, S',
              ean_code: 2200015601034,
              regional_wise_quantity: {
                aux: 6,
                dxb: 6,
                aln: 2,
                omn: 6,
                qtr: 6,
                bah: 4,
                kwt: 4,
                ksa: 6,
              },
              selling_price: {
                sp_ae: 45.0,
                sp_qa: 45.0,
                sp_sa: 49.0,
                bh: 4.9,
                sp_om: 4.5,
                sp_kw: 4.0,
              },
            },
            {
              fair_article: 2312376002,
              tag_article: 2345975002,
              tag_description: 'Ladies Tee S/S CORL150CD AW24, M',
              ean_code: 2200015601041,
              regional_wise_quantity: {
                aux: 12,
                dxb: 12,
                aln: 4,
                omn: 12,
                qtr: 12,
                bah: 8,
                kwt: 8,
                ksa: 12,
              },
              selling_price: {
                sp_ae: 45.0,
                sp_qa: 45.0,
                sp_sa: 49.0,
                bh: 4.9,
                sp_om: 4.5,
                sp_kw: 4.0,
              },
            },
            {
              fair_article: 2312376003,
              tag_article: 2345975003,
              tag_description: 'Ladies Tee S/S CORL150CD AW24, L',
              ean_code: 2200015601058,
              regional_wise_quantity: {
                aux: 24,
                dxb: 24,
                aln: 8,
                omn: 24,
                qtr: 24,
                bah: 16,
                kwt: 16,
                ksa: 24,
              },
              selling_price: {
                sp_ae: 45.0,
                sp_qa: 45.0,
                sp_sa: 49.0,
                bh: 4.9,
                sp_om: 4.5,
                sp_kw: 4.0,
              },
            },
            {
              fair_article: 2312376004,
              tag_article: 2345975004,
              tag_description: 'Ladies Tee S/S CORL150CD AW24, XL',
              ean_code: 2200015601065,
              regional_wise_quantity: {
                aux: 18,
                dxb: 18,
                aln: 6,
                omn: 18,
                qtr: 18,
                bah: 12,
                kwt: 12,
                ksa: 18,
              },
              selling_price: {
                sp_ae: 45.0,
                sp_qa: 45.0,
                sp_sa: 49.0,
                bh: 4.9,
                sp_om: 4.5,
                sp_kw: 4.0,
              },
            },
            {
              fair_article: 2312376005,
              tag_article: 2345975005,
              tag_description: 'Ladies Tee S/S CORL150CD AW24, XXl',
              ean_code: 2200015601072,
              regional_wise_quantity: {
                aux: 12,
                dxb: 12,
                aln: 4,
                omn: 12,
                qtr: 12,
                bah: 8,
                kwt: 8,
                ksa: 12,
              },
              selling_price: {
                sp_ae: 45.0,
                sp_qa: 45.0,
                sp_sa: 49.0,
                bh: 4.9,
                sp_om: 4.5,
                sp_kw: 4.0,
              },
            },
          ],
        },
      },
    ],
    change_requests: [],
    attachments: [],
  },
];
